version: '3.8'

services:
  sentinel-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sentinel_backend
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - .env
    volumes:
      - ./evidence:/app/evidence

  sentinel-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: sentinel_dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./evidence:/app/evidence
    depends_on:
      - sentinel-backend